import type { Artifact, ForgePilotRun, PlanStep, TimelineStep } from "./types";

const completedPlanSteps: PlanStep[] = [
  {
    id: "plan-trigger",
    title: "Trigger received",
    description: "Normalize the incoming goal and create a local runtime run record.",
    status: "completed",
    riskLevel: "low",
  },
    {
      id: "plan-build",
      title: "Build deterministic local plan",
      description: "Use the built-in local planner when Qwen Cloud is not configured.",
      status: "completed",
      riskLevel: "low",
    },
  {
    id: "plan-scan",
    title: "Scan project status",
    description: "Inspect the project state represented by this MVP runtime.",
    status: "completed",
    toolName: "scan_project_status",
    riskLevel: "low",
  },
  {
    id: "plan-checklist",
    title: "Generate submission checklist",
    description: "Produce a Qwen Cloud hackathon readiness checklist.",
    status: "completed",
    toolName: "generate_submission_checklist",
    riskLevel: "low",
  },
  {
    id: "plan-devpost",
    title: "Draft Devpost description",
    description: "Draft honest submission copy without claiming live Qwen integration.",
    status: "completed",
    toolName: "draft_devpost_description",
    riskLevel: "medium",
  },
  {
    id: "plan-demo-script",
    title: "Generate demo script",
    description: "Create a 3-minute walkthrough script for judges.",
    status: "completed",
    toolName: "generate_demo_script",
    riskLevel: "low",
  },
  {
    id: "plan-linkedin",
    title: "Draft LinkedIn post",
    description: "Create a restrained founder-style post for later review.",
    status: "completed",
    toolName: "draft_linkedin_post",
    riskLevel: "medium",
  },
  {
    id: "plan-architecture",
    title: "Generate architecture summary",
    description: "Summarize the local runtime flow and next Qwen phase.",
    status: "completed",
    toolName: "generate_architecture_summary",
    riskLevel: "low",
  },
  {
    id: "plan-approval",
    title: "Request human approval",
    description: "Pause before final artifact generation and completion.",
    status: "completed",
    toolName: "request_human_approval",
    requiresApproval: true,
    riskLevel: "medium",
  },
  {
    id: "plan-write",
    title: "Write markdown artifact pack",
    description: "Simulate safe artifact writing by creating artifact objects in state.",
    status: "completed",
    toolName: "write_markdown_file",
    riskLevel: "medium",
  },
  {
    id: "plan-report",
    title: "Complete run report",
    description: "Seal the run report with timeline, tools, approvals, and artifacts.",
    status: "completed",
    riskLevel: "low",
  },
];

export const demoTimeline: TimelineStep[] = [
  {
    id: "step-trigger",
    title: "Trigger received",
    status: "completed",
    timestamp: "2026-07-06T09:00:00.000Z",
    description: "Manual command accepted and normalized into a run objective.",
    toolName: "trigger.engine",
    riskLevel: "low",
  },
  {
    id: "step-plan",
    title: "Local fallback plan selected",
    status: "completed",
    timestamp: "2026-07-06T09:00:16.000Z",
    description: "Auto mode used the deterministic local planner because Qwen env vars were not configured.",
    toolName: "local.planner",
    riskLevel: "medium",
  },
  {
    id: "step-scan",
    title: "Project scan started",
    status: "completed",
    timestamp: "2026-07-06T09:00:42.000Z",
    description: "Local repository metadata, route structure, and docs targets were inspected.",
    toolName: "repo.scan",
    riskLevel: "low",
  },
  {
    id: "step-checklist",
    title: "Submission checklist generated",
    status: "completed",
    timestamp: "2026-07-06T09:01:18.000Z",
    description: "Runtime assembled a track-specific checklist for Devpost readiness.",
    toolName: "checklist.writer",
    riskLevel: "low",
  },
  {
    id: "step-devpost",
    title: "Devpost draft prepared",
    status: "completed",
    timestamp: "2026-07-06T09:02:04.000Z",
    description: "Submission narrative, differentiators, and MVP scope were drafted.",
    toolName: "devpost.drafter",
    riskLevel: "medium",
  },
  {
    id: "step-script",
    title: "Demo script drafted",
    status: "completed",
    timestamp: "2026-07-06T09:02:50.000Z",
    description: "A concise demo flow was generated for a two-minute judge walkthrough.",
    toolName: "demo.script.writer",
    riskLevel: "low",
  },
  {
    id: "step-approval",
    title: "Human approval requested",
    status: "approval_required",
    timestamp: "2026-07-06T09:03:20.000Z",
    description: "Runtime paused before writing outward-facing submission artifacts.",
    toolName: "approval.gate",
    riskLevel: "high",
  },
  {
    id: "step-artifacts",
    title: "Artifact pack written",
    status: "completed",
    timestamp: "2026-07-06T09:04:12.000Z",
    description: "Approved markdown and JSON artifacts were written to the local workspace.",
    toolName: "artifact.writer",
    riskLevel: "medium",
  },
  {
    id: "step-complete",
    title: "Run completed",
    status: "completed",
    timestamp: "2026-07-06T09:04:35.000Z",
    description: "Flight Recorder sealed the run report with tool calls and approvals.",
    toolName: "flight.recorder",
    riskLevel: "low",
  },
];

export const demoArtifacts: Artifact[] = [
  {
    id: "artifact-submission-pack",
    fileName: "submission-pack.md",
    kind: "markdown",
    description: "Hackathon submission narrative, differentiators, and MVP scope.",
    status: "written",
    path: "artifacts/submission-pack.md",
    size: "8.4 KB",
  },
  {
    id: "artifact-demo-script",
    fileName: "demo-script.md",
    kind: "script",
    description: "Presenter-ready demo sequence with timing and proof points.",
    status: "written",
    path: "artifacts/demo-script.md",
    size: "5.1 KB",
  },
  {
    id: "artifact-linkedin",
    fileName: "linkedin-post.md",
    kind: "markdown",
    description: "Short public launch post drafted for review before publishing.",
    status: "drafted",
    path: "artifacts/linkedin-post.md",
    size: "2.2 KB",
  },
  {
    id: "artifact-architecture",
    fileName: "architecture-summary.md",
    kind: "summary",
    description: "Runtime flow explanation for judges and technical reviewers.",
    status: "written",
    path: "artifacts/architecture-summary.md",
    size: "4.7 KB",
  },
  {
    id: "artifact-report",
    fileName: "run-report.json",
    kind: "json",
    description: "Structured event log with tool calls, risk levels, and approvals.",
    status: "written",
    path: "artifacts/run-report.json",
    size: "11.9 KB",
  },
];

export const demoRun: ForgePilotRun = {
  id: "run-qwen-submission-pack",
  title: "Qwen Cloud submission pack",
  goal: "Prepare my Qwen Cloud hackathon submission pack.",
  command: "Prepare my Qwen Cloud hackathon submission pack.",
  triggerType: "manual",
  status: "completed",
  summary:
    "Generated a submission checklist, Devpost draft, demo script, launch post, architecture summary, and run report.",
  finalSummary:
    "Demo run completed with local artifacts, approval record, and Flight Recorder proof.",
  createdAt: "2026-07-06T09:00:00.000Z",
  startedAt: "2026-07-06T09:00:00.000Z",
  completedAt: "2026-07-06T09:04:35.000Z",
  plannerModeRequested: "auto",
  plannerModeUsed: "local_fallback",
  qwenConfigured: false,
  plannerWarnings: [
    "Qwen Cloud env vars are not configured, so auto mode used the local deterministic planner.",
  ],
  planSteps: completedPlanSteps,
  timeline: demoTimeline,
  toolCalls: [
    {
      id: "tool-plan",
      name: "local.planner",
      provider: "local",
      status: "completed",
      riskLevel: "medium",
      inputSummary: "Convert a messy submission-prep request into an ordered workflow.",
      outputSummary: "Nine-step plan with scan, draft, approval, write, and report phases.",
      startedAt: "2026-07-06T09:00:08.000Z",
      completedAt: "2026-07-06T09:00:16.000Z",
    },
    {
      id: "tool-scan",
      name: "repo.scan",
      provider: "local",
      status: "completed",
      riskLevel: "low",
      inputSummary: "Inspect local project context without sending files to hosted services.",
      outputSummary: "Route list, package metadata, and documentation targets collected.",
      startedAt: "2026-07-06T09:00:39.000Z",
      completedAt: "2026-07-06T09:00:58.000Z",
    },
    {
      id: "tool-artifacts",
      name: "artifact.writer",
      provider: "runtime",
      status: "completed",
      riskLevel: "medium",
      inputSummary: "Persist approved markdown and JSON outputs to local artifact paths.",
      outputSummary: "Five artifact records written and indexed by Flight Recorder.",
      startedAt: "2026-07-06T09:03:58.000Z",
      completedAt: "2026-07-06T09:04:12.000Z",
    },
  ],
  approvalRequests: [
    {
      id: "approval-public-copy",
      title: "Approve outward-facing submission copy",
      summary:
        "Review Devpost draft, LinkedIn post, and claims before writing final artifacts.",
      status: "approved",
      riskLevel: "high",
      requestedAt: "2026-07-06T09:03:20.000Z",
      approvedAt: "2026-07-06T09:03:51.000Z",
      approver: "Human operator",
    },
  ],
  artifacts: demoArtifacts,
};

export const recentRuns: ForgePilotRun[] = [
  demoRun,
  {
    id: "run-local-readme-refresh",
    title: "Repository readiness sweep",
    goal: "Audit my project docs and tell me what is missing before submission.",
    command: "Audit my project docs and tell me what is missing before submission.",
    triggerType: "manual",
    status: "completed",
    summary: "Scanned local docs, generated gaps, and produced a proof checklist.",
    finalSummary: "Documentation gaps were summarized for a local readiness pass.",
    createdAt: "2026-07-05T16:10:00.000Z",
    startedAt: "2026-07-05T16:10:00.000Z",
    completedAt: "2026-07-05T16:13:28.000Z",
    plannerModeRequested: "local",
    plannerModeUsed: "local",
    qwenConfigured: false,
    plannerWarnings: [],
    planSteps: [],
    timeline: [],
    toolCalls: [],
    approvalRequests: [],
    artifacts: [],
  },
  {
    id: "run-webhook-demo",
    title: "Webhook intake rehearsal",
    goal: "When the demo webhook fires, create a compact run report.",
    command: "When the demo webhook fires, create a compact run report.",
    triggerType: "webhook",
    status: "awaiting_approval",
    summary: "Received webhook payload, drafted actions, and paused at approval.",
    createdAt: "2026-07-05T11:42:00.000Z",
    startedAt: "2026-07-05T11:42:00.000Z",
    plannerModeRequested: "auto",
    plannerModeUsed: "local_fallback",
    qwenConfigured: false,
    plannerWarnings: [
      "Webhook rehearsal used local fallback because Qwen Cloud credentials were not configured.",
    ],
    planSteps: [],
    timeline: [],
    toolCalls: [],
    approvalRequests: [],
    artifacts: [],
  },
];

export const runtimeStats = [
  {
    label: "Workflows executed",
    value: "128",
    detail: "seeded local runtime history",
  },
  {
    label: "Tools available",
    value: "8",
    detail: "planner, scanner, writers, gates",
  },
  {
    label: "Approval gates",
    value: "37",
    detail: "human checkpoints recorded",
  },
  {
    label: "Artifacts generated",
    value: "214",
    detail: "markdown, JSON, scripts, reports",
  },
];
